version: "3.8"

services:
  byt-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: byt-frontend
    # ports:
    #   - "3000:80"
    environment:
      - NODE_ENV=production  # Or 'production'
      - VITE_HOST=http://api.baytalkhyataonline.top/api/v1
      - VITE_SOCKET=http://api.baytalkhyataonline.top
    networks:
      - byt-network


networks:
  byt-network:
    name: byt-network
    driver: bridge
